### ISSUE TITLE
Fix this program

### ISSUE THREAD

**Issue by shahrajesh2006** [shahrajesh2006/RainingRobots#2]
primes = [2, 3, 5, 7]
student=["Vir","Vihaan","Aarav","Samith","Neel"]
for myvariable in student:
    print("Length of name"+myvariable+"is:%d", % len(myvariable))

myvariable="rajesh"
print(myvariable)

**Comment by ghost** [comment]
This is my code

primes = [2, 3, 5, 7]
student=["Vir","Vihaan","Aarav","Samhith","Neel"]
for myvariable in student:
 print("Length of name"+myvariable+"" " is: %d" % len (myvariable))

myvariable="rajesh"
print(myvariable)



i added a space between the person's name and "is".  I also got rid of the comma after the double quotations.

**Comment by shahrajesh2006** [comment]
Nice Work!
